/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "simple.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Request, Request, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(Ping, Ping, AUTO)


PB_BIND(MemOp, MemOp, AUTO)


PB_BIND(RequestInfo, RequestInfo, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(SetupSlots, SetupSlots, AUTO)


PB_BIND(InjectUART, InjectUART, AUTO)


PB_BIND(UartData, UartData, AUTO)



